# Generated by check_harden.py on every run - edit constraints.sdc, not this.
# LibreLane's base SDC: the primary clock (CLOCK_PORT at CLOCK_PERIOD, both
# spec.yaml's), I/O delays, drive and load - what a one-clock harden gets.
source $::env(SCRIPTS_DIR)/base.sdc
# The design's other clocks, generated clocks and exceptions.
source {/home/ihsan/.cc/worktrees/ece298a/pll/blocks/pll/digital/harden/constraints.sdc}
set_clock_uncertainty $::env(CLOCK_UNCERTAINTY_CONSTRAINT) [all_clocks]
set_clock_transition $::env(CLOCK_TRANSITION_CONSTRAINT) [all_clocks]
if { [info exists ::env(OPENLANE_SDC_IDEAL_CLOCKS)] && $::env(OPENLANE_SDC_IDEAL_CLOCKS) } {
    unset_propagated_clock [all_clocks]
} else {
    set_propagated_clock [all_clocks]
}
