/* generated by engine/lib/ttlib.py::generate_glsim_harness - do not hand-edit. */
`default_nettype none

module ihsan_sa_pll (
    input  wire clk,
    output wire clk_fb,
    output wire cp_trim0,
    output wire cp_trim1,
    input  wire [1:0] cp_trim_in,
    output wire lock,
    input  wire [2:0] n_sel,
    output wire obs_out,
    input  wire obs_sel,
    output wire pfd_dn,
    output wire pfd_up,
    output wire pll_en,
    input  wire pll_en_in,
    input  wire rst_n,
    input  wire vco_out
);
  wire [7:0] tt_ui_in = {obs_sel, pll_en_in, 1'b0, 1'b0, vco_out, n_sel[2], n_sel[1], n_sel[0]};
  wire [7:0] tt_uio_in = {1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, cp_trim_in[1], cp_trim_in[0]};
  wire [7:0] tt_uo_out;
  wire [7:0] tt_uio_out;
  wire [7:0] tt_uio_oe;
  wire tt_ena = 1'b1;
  wire tt_clk = clk;
  wire tt_rst_n = rst_n;
  assign clk_fb = tt_uo_out[1];
  assign cp_trim0 = tt_uo_out[6];
  assign cp_trim1 = tt_uo_out[7];
  assign lock = tt_uo_out[2];
  assign obs_out = tt_uo_out[0];
  assign pfd_dn = tt_uo_out[4];
  assign pfd_up = tt_uo_out[3];
  assign pll_en = tt_uo_out[5];

  tt_um_ihsan_sa_pll dut (
      .ui_in(tt_ui_in), .uo_out(tt_uo_out), .uio_in(tt_uio_in),
      .uio_out(tt_uio_out), .uio_oe(tt_uio_oe), .ena(tt_ena),
      .clk(tt_clk), .rst_n(tt_rst_n)
  );
endmodule
`default_nettype wire
